import sqlite3
import json
import os

def create_database():
    """
    Creates a SQLite database with Karnataka government schemes and services.
    """
    db_file = 'karnataka_schemes.db'
    
    # Remove the old database file if it exists for a clean start
    if os.path.exists(db_file):
        os.remove(db_file)
        print(f"Removed existing database file: {db_file}")

    # The scheme data converted to a Python list of dictionaries
    schemes_data = [
        {"scheme_id": 47, "scheme_name": "Arivu Educational Renewal Loan Scheme", "department_id": 1150, "department_name": "Karnataka Minorities Development Corporation (KMDC)", "definition": "You will receive a loan up to ₹1,00,000 at 2% interest per annum.", "eligibility": "Applicant must have passed the previous year’s examination.", "procedure": ["Applicant submits the application.", "Application reaches Case Worker (L1, District Level) → verifies and forwards.", "Program Officer (L2, District Level) reviews and forwards.", "Disbursement Officer (L3, State Level) reviews and forwards.", "Application pushed to DBT for disbursement."], "supporting_documents": ["Fee Receipt", "Study Certificate", "Upload Claim Letter including Sanction Order", "Previous Year Marksheet", "Parent Approval Letter", "Collateral Letter"], "charges": "₹30"},
        {"scheme_id": 48, "scheme_name": "Unemployment Allowance for Disabilities", "department_id": 1151, "department_name": "Department for Empowerment of Differently Abled and Senior Citizens", "definition": "If approved, the applicant will receive ₹1000/month until employed or reaches 45 years of age.", "eligibility": "Applicant must have a Registration Certificate from an Employment Exchange.", "procedure": ["Applicant submits the application.", "Case Worker (L1, District Level) verifies and forwards to DDWO.", "DDWO (L2) sanctions and forwards to DBT.", "DBT disburses the amount to the beneficiary."], "supporting_documents": ["Disability Certificate/UDID Card (mandatory)", "Proof of Unemployment attested by a Gazetted Officer", "Registration Certificate from Employment Exchange/Special Employment Exchange"], "charges": "NA"},
        {"scheme_id": 49, "scheme_name": "Prize Money for Merit Scholarship – Disability Students", "department_id": 1151, "department_name": "Department for Empowerment of Differently Abled and Senior Citizens", "definition": "If approved, the applicant will receive a ₹12,000 scholarship.", "eligibility": "Applicant must have scored ≥60% marks in the previous year's entrance exam.", "procedure": ["Applicant submits the application.", "Case Worker (L1, District Level) verifies and forwards to DDWO.", "DDWO (L2) sanctions and forwards to DBT.", "DBT disburses the amount to the beneficiary."], "supporting_documents": ["Disability Certificate/UDID Card (mandatory)", "Certificate from School Headmaster/College Principal", "Year of passing proof with ≥60% marks", "Marks Sheet of the exam"], "charges": "NA"},
        {"scheme_id": 42, "scheme_name": "State Scholarship Portal (SSP) – Post-Matric", "department_id": 1145, "department_name": "e-Governance", "definition": "An integrated State Scholarship Portal developed by the Center for e-Governance for sanctioning Post-Matric Scholarships under Government of Karnataka (GoK) schemes. Benefits are transferred directly to Aadhaar-seeded accounts via Direct Benefit Transfer (DBT).", "eligibility": "As per 2021–22 SSP criteria.", "procedure": "NA", "supporting_documents": ["e-Attestation is used in SSP, validated by the electronic signature of the attestation officer.", "The student should enter details like caste/income certificate number, Aadhaar, UDID, University registration number, counselling number, etc."], "charges": "NA"},
        {"scheme_id": 44, "scheme_name": "Hiring of District Consultant – FRUITS (on contract basis)", "department_id": 1145, "department_name": "e-Governance", "definition": "Hiring district-level consultants under the FRUITS scheme for a one-year contract under the District Administration.", "eligibility": ["BE in Computer Science/Electronics/IT OR", "Degree in Agriculture/Horticulture/Sericulture/Veterinary Sciences/Fisheries/B.Tech Agriculture OR", "BCA/MCA"], "procedure": "Hiring of one consultant per district.", "supporting_documents": ["SSLC Marks Card", "Degree Certificate & Marks Card", "Experience Certificate"], "charges": "Rs.25"},
        {"scheme_id": 50, "scheme_name": "Gruha Jyothi Scheme", "department_id": 1149, "department_name": "Energy Department", "definition": "A Karnataka government scheme providing up to 200 free electricity units per month for households. In 2024, a 10-unit buffer was introduced for households consuming less than 48 units monthly.", "benefits": "Up to 200 units/month of free electricity for eligible households.", "eligibility": ["Must be a resident of Karnataka.", "Should have a residential electricity connection in the applicant’s name.", "Aadhaar linkage and electricity consumption verification are required.", "Application through the Seva Sindhu portal with proof of consumption & identity."], "required_information": ["Full name of the applicant (as per Aadhaar).", "Aadhaar number.", "Registered electricity account/connection number.", "Electricity supply company (BESCOM, HESCOM, MESCOM, GESCOM, etc.).", "Monthly electricity consumption history (last 6 months).", "Mobile number linked with Aadhaar.", "Email address (optional, for communication).", "Proof of residence (address, voter ID, ration card, etc.)."]},
        {"scheme_id": 32, "scheme_name": "Transfer of Connection/Ownership (Industrial/Commercial/Others)", "department_id": 1137, "department_name": "Bangalore Water Supply and Sewerage Board (BWSSB)", "definition": "Change of name in BWSSB water/sanitary connections due to the transfer of property ownership.", "eligibility": "Bengaluru residents with a valid RR Number and BWSSB connection.", "procedure": ["Applicant submits an online application with details (Address, Khatha, PID, RR No., new consumer name).", "A GSC code is generated, and the application is processed within 10 days.", "AEE verifies reports from AE/WI & Revenue Manager and approves the change.", "A demand note of Rs.250 is generated. The consumer pays online, and the ownership is updated."], "supporting_documents": ["Sale Deed", "Khatha Extract", "Recent tax paid receipt", "Water bill", "Affidavit"], "charges": "Rs.250"},
        {"scheme_id": 29, "scheme_name": "Permission for New/Additional Water Supply & UGD Connection (Residential buildings excluding Apartments)", "department_id": 1137, "department_name": "Bangalore Water Supply and Sewerage Board (BWSSB)", "definition": "Permission for new or additional water supply and underground drainage (UGD) connection for residential buildings, excluding apartments.", "eligibility": "Owners/occupiers of buildings in BWSSB serviceable areas who want a water/sanitary connection.", "procedure": ["The applicant submits an online form with required documents (photos, sanction plan, road cutting endorsement, tax receipt, occupancy certificate if multi-storey, khata, Rain Water Harvesting photo, etc.).", "A Water Inspector/Assistant Engineer inspects the premises and provides a recommendation.", "The AEE sanctions the connections at the subdivision office.", "For multi-storey cases involving prorata charges, measurements are taken, and the file is escalated to higher authorities depending on the delegation of powers."], "supporting_documents": ["Building plan", "Building photo with owner", "Lease cum Sale Deed / Sale Deed", "Khata", "Previous receipts (if available)", "Rain Water Harvesting structure (if applicable)", "CFO (if STP is applicable)", "Occupancy Certificate (if applicable)", "NOC (if applicable)"], "charges": "Rs.30"},
        {"scheme_id": 30, "scheme_name": "Permission for New/Additional Water Supply & UGD Connection (Multi-storied Buildings)", "department_id": 1137, "department_name": "Bangalore Water Supply and Sewerage Board (BWSSB)", "definition": "Permission for new or additional water supply and underground drainage (UGD) connection for multi-storied buildings.", "eligibility": "Owners/occupiers of buildings in BWSSB serviceable areas who want a water/sanitary connection.", "procedure": ["The applicant submits an online form with required documents. The Occupancy Certificate is mandatory.", "A Water Inspector/Assistant Engineer inspects the premises and provides a recommendation.", "The AEE sanctions the connections at the subdivision office.", "For multi-storied buildings, prorata charges are mandatory. Measurements are taken, and the file is escalated to higher authorities."], "supporting_documents": ["Building plan", "Building photo with owner", "Lease cum Sale Deed / Sale Deed", "Khata", "Previous receipts (if available)", "Rain Water Harvesting structure (if applicable)", "CFO (if STP is applicable)", "Occupancy Certificate (mandatory)", "NOC (if applicable)"], "charges": "Rs.30"},
        {"scheme_id": 31, "scheme_name": "Replacement of Faulty Meters", "department_id": 1137, "department_name": "Bangalore Water Supply and Sewerage Board (BWSSB)", "definition": "Residents can request the replacement of faulty water meters.", "eligibility": "Bengaluru residents with a valid RR Number and a water/sanitary connection under BWSSB.", "procedure": ["The applicant submits details (RR No., meter make, meter no., last reading) online or at the subdivision office.", "AEE forwards the request to a Water Inspector for inspection.", "The Water Inspector observes the meter for two consecutive water supplies and submits a report.", "If found faulty, the AE recommends replacement. The AEE approves based on stock availability.", "A Draftsman issues a new meter to the Water Inspector, who then installs it."], "supporting_documents": ["Latest Water Bill"], "charges": "Rs.20"},
        {"scheme_id": 25, "scheme_name": "Correction in Marks Card", "department_id": 1133, "department_name": "Education (Examination & Certification Services)", "definition": "Application for correction in an existing marks card.", "eligibility": "Not applicable.", "procedure": ["The applicant fills the form and uploads the necessary documents.", "The department processes the valid application.", "The applicant is notified upon delivery."], "supporting_documents": ["Copy of marks card issued earlier.", "Copy of SSLC/PUC marks card."], "charges": "Rs. 25"},
        {"scheme_id": 26, "scheme_name": "Issue of Consolidated Marks Card", "department_id": 1133, "department_name": "Education (Examination & Certification Services)", "definition": "Application for the issuance of a consolidated marks card.", "eligibility": "Not applicable.", "procedure": ["The applicant fills the form and uploads the necessary documents.", "The department processes the valid application.", "The applicant is notified upon delivery."], "supporting_documents": ["Copy of all relevant result sheets.", "Copy of previously issued marks card."], "charges": "Rs. 20"},
        {"scheme_id": 27, "scheme_name": "Issue of Duplicate Marks Card", "department_id": 1133, "department_name": "Education (Examination & Certification Services)", "definition": "Application for a duplicate marks card in case of loss of the original.", "eligibility": "Not applicable.", "procedure": ["The applicant fills the form and uploads the necessary documents.", "The department processes the valid application.", "The applicant is notified upon delivery."], "supporting_documents": ["Photocopy of earlier marks card.", "Copy of police complaint for loss.", "Copy of newspaper advertisement regarding loss."], "charges": "Rs. 20"},
        {"scheme_id": 28, "scheme_name": "Issue of Transfer Certificate", "department_id": 1133, "department_name": "Education (Examination & Certification Services)", "definition": "Application for the issuance of a Transfer Certificate (TC).", "eligibility": "Not applicable.", "procedure": ["The applicant fills the form and uploads the necessary documents.", "The department processes the valid application.", "The applicant is notified upon delivery."], "supporting_documents": ["Attested copies of marks cards of all semesters/years.", "Attested copy of SSLC marks card.", "No due certificate from the library and office.", "Attested caste certificate (if applicable)."], "charges": "Rs. 20"},
        {"scheme_id": 18, "scheme_name": "Application for Clearance Certificate (High rise Building)", "department_id": 1120, "department_name": "Karnataka State Fire and Emergency Services", "definition": "Application for obtaining a Clearance Certificate for high-rise buildings.", "eligibility": "Building height must be above 15 meters.", "procedure": "Not specified.", "supporting_documents": ["Covering Letter", "Site Plan", "Ground Floor Plan", "Typical Floor Plan", "Elevation", "Section", "Fire Schematic", "Built-up Area Statement", "Ownership Document"], "charges": "NA"},
        {"scheme_id": 19, "scheme_name": "Application for No Objection Certificate (High rise Building)", "department_id": 1120, "department_name": "Karnataka State Fire and Emergency Services", "definition": "Application for obtaining a No Objection Certificate (NOC) for high-rise buildings.", "eligibility": "Building height must be above 15 meters.", "procedure": "Not specified.", "supporting_documents": ["Covering Letter", "Site Plan", "Ground Floor Plan", "Typical Floor Plan", "Elevation", "Section", "Fire Schematic", "Built-up Area Statement", "Ownership Document"], "charges": "Residential: Rs. 35/- per sq.mtr or Rs. 2,50,000/- (whichever is higher). Non-residential/Other: Rs. 60/- per sq.mtr or Rs. 5,00,000/- (whichever is higher)."},
        {"scheme_id": 11, "scheme_name": "Admission to Post-matric Hostels", "department_id": 1114, "department_name": "Backward Classes Welfare Department", "definition": "Application for admission to post-matric hostels for students.", "eligibility": "According to a notification issued by the Department.", "procedure": ["The student submits the online application and uploads the required documents.", "Submit hard copies of the application and documents to the Taluka Backward Classes Welfare Office.", "The department verifies the application and sanctions the admission."], "supporting_documents": ["Caste and Income Certificate.", "Previous year’s marks card.", "Aadhaar UID (if available).", "Ration Card copy (if available).", "Passport size photo."], "charges": "NIL"},
        {"scheme_id": 12, "scheme_name": "Pre-examination Training to BC Students", "department_id": 1114, "department_name": "Backward Classes Welfare Department", "definition": "Application for pre-examination training for Backward Classes (BC) students.", "eligibility": "According to a notification issued by the Department.", "procedure": ["The student submits the online application and uploads the required documents.", "Submit hard copies of the application and documents to the District Backward Classes Welfare Office.", "The department verifies the application and sanctions training benefits."], "supporting_documents": ["SSLC Marks Card.", "Caste and Income Certificate.", "Degree Certificate.", "Aadhaar Card.", "Passport size photo.", "Physically challenged certificate (if applicable).", "Bank Passbook (front page)."], "charges": "NIL"},
        {"scheme_id": 13, "scheme_name": "Defence Force Training", "department_id": 1114, "department_name": "Backward Classes Welfare Department", "definition": "Application for enrolment in Defence Force Training.", "eligibility": "According to a notification issued by the Department.", "procedure": ["Submit the application with attachments and fee payment.", "The application is processed by BESCOM.", "A Security Deposit (if applicable) is to be paid separately.", "The applicant receives confirmation upon completion."], "supporting_documents": ["SSLC (10th) Marks Card.", "PUC Marks Card.", "Caste Certificate.", "Income Certificate.", "Aadhaar Card.", "Medical Certificate.", "NCC ‘C’ Certificate (if available).", "Candidate photo with signature."], "charges": "Rs. 40"},
        {"scheme_id": 14, "scheme_name": "Pre-matric Scholarship to BC Students", "department_id": 1114, "department_name": "Backward Classes Welfare Department", "definition": "Application for pre-matric scholarship for Backward Classes (BC) students.", "eligibility": "According to a notification issued by the Department.", "procedure": ["The student submits the online application and uploads the required documents.", "The department verifies the application and sanctions the scholarship."], "supporting_documents": ["Student’s SATS ID.", "Aadhaar or EID number of student & parent.", "Mobile Number.", "Caste and Income Certificate."], "charges": "NIL"},
        {"scheme_id": 7, "scheme_name": "Application for Caste Verification Report – OBC", "department_id": 1114, "department_name": "Backward Classes Welfare Department", "definition": "This service allows a recruiting department/organisation to seek verification and authenticity of caste and income certificates of applicants from the District Commissioner's committee.", "eligibility": "Shortlisted candidates from a respective recruiting organisation.", "procedure": ["The recruiting department informs the DC committee/District Backward Classes office and the candidate.", "The applicant fills the form in the Seva Sindhu Portal.", "A district officer verifies the documents and initiates a field inspection by the Taluk officer.", "The Taluk officer conducts the inspection and submits a report.", "The district officer reviews the report and sets up a DC committee meeting.", "The DC committee decides on the issuance of the Sindhutva Pramana Patra."], "supporting_documents": ["Primary school admission extract (1st Standard only).", "Caste Certificate issued by Tahsildar.", "Passport Photo.", "Father’s caste certificate from Tahsildar (or uncle/aunt’s certificate if not available).", "Father’s school admission extract (or uncle/aunt’s extract if father is illiterate).", "Proof of employment of candidate/parents/spouse.", "Last 12 months’ salary slips.", "RTC Certificate of properties in candidate/parents/spouse’s name.", "Land holding certificate from Tahsildar.", "Landless certificate from Tahsildar.", "Ration Card.", "Aadhaar copy.", "Family tree issued by Tahsildar."], "charges": "Rs. 35"},
        {"scheme_id": 8, "scheme_name": "Post-matric Scholarship to BC Students", "department_id": 1114, "department_name": "Backward Classes Welfare Department", "definition": "Application for post-matric scholarship for Backward Classes (BC) students.", "eligibility": "As per Department notification.", "procedure": ["The student submits an online application and uploads documents.", "Submit hard copies of the application and documents to the college.", "The department verifies the application and sanctions the scholarship."], "supporting_documents": ["Caste and Income Certificate.", "Previous year’s marks card.", "Aadhaar UID (if available).", "Ration Card copy (if available).", "Passport size photo.", "Bank account in a nationalized bank (name as per SSLC certificate)."], "charges": "NA"},
        {"scheme_id": 9, "scheme_name": "Vidyasiri – Food and Accommodation Scheme", "department_id": 1114, "department_name": "Backward Classes Welfare Department", "definition": "Application for the Vidyasiri scheme, which provides financial assistance for food and accommodation to students.", "eligibility": "As per Department notification.", "procedure": ["The student submits an online application and uploads documents.", "Submit hard copies of the application and documents to the college.", "The department verifies the application and sanctions the amount."], "supporting_documents": ["Caste and Income Certificate.", "Previous year’s marks card.", "Aadhaar UID (if available).", "Ration Card copy (if available).", "Passport size photo.", "Bank account in a nationalized bank (name as per SSLC certificate)."], "charges": "NA"},
        {"scheme_id": 10, "scheme_name": "Special Incentives Scholarship to NT/SNT Students", "department_id": 1114, "department_name": "Backward Classes Welfare Department", "definition": "Application for special incentive scholarships for Nomadic Tribes (NT) and Semi-Nomadic Tribes (SNT) students.", "eligibility": "As per Department notification.", "procedure": ["The student submits an online application and uploads documents.", "Submit hard copies of the application and documents to the college.", "The department verifies the application and sanctions the amount."], "supporting_documents": ["Caste and Income Certificate.", "Previous year’s marks card.", "Aadhaar UID (if available).", "Ration Card copy (if available).", "Passport size photo.", "Bank account in a nationalized bank (name as per SSLC certificate)."], "charges": "NA"},
        {"scheme_id": 3, "scheme_name": "Swa Sahaya Sangagalige Uttejena (Self Help Group Encouragement Scheme)", "department_id": 1150, "department_name": "Karnataka Minorities Development Corporation (KMDC)", "definition": "Each member of an eligible self-help group will receive Rs. 15,000.", "eligibility": "Female, aged between 21–50 years, belonging to OBC – Veerashaiva Lingayat Community. The applicant must fall under the caste list provided by the Corporation.", "procedure": ["The applicant logs into their account.", "Search for the scheme in the search bar.", "Confirm details like Religion, Caste Category, Gender, Domicile, Age, Farmer status, and caste eligibility under the corporation’s list."], "supporting_documents": ["Caste & Annual Income Certificate (from Tahsildar/Revenue Officer, confirming Veerashaiva Lingayat Community).", "Aadhaar Card / Ration Card / Electoral ID (Proof of Residence).", "Two recent passport size photos.", "Self Help Group Conduct Book & Bank Account details (Account Number, IFSC, Passbook copy).", "Undertaking by all SHG members for loan security.", "Declaration of assets and liabilities of the applicant and guarantor.", "Aadhaar card copy of the applicant.", "Confirmation that the SHG has not taken loans from other departments/banks."], "charges": "Rs. 30"},
        {"scheme_id": 4, "scheme_name": "Arivu Educational Loan Scheme (Fresh) – 2022-23 / Basava Belagu", "department_id": 1150, "department_name": "Karnataka Minorities Development Corporation (KMDC)", "definition": "A loan up to Rs. 1,00,000 per annum for 5 years from the Corporation for education purposes.", "eligibility": "Must belong to the OBC – Veerashaiva Lingayat Community. Annual family income up to Rs. 3,50,000. Age: 18–30 years.", "procedure": ["The applicant submits the application.", "The application reaches the Case Worker (L1 Officer) at the District Level.", "The verified application moves to the Program Officer (L2 Officer) at the District Level.", "Then to the Disbursement Officer (L3 Officer) at the State Level.", "Finally, it is pushed to DBT for disbursement."], "supporting_documents": ["Aadhaar Card", "Caste Certificate", "Income Certificate", "Parent Approval Letter", "Collateral Letter"], "charges": "Rs. 30"},
        {"scheme_id": 5, "scheme_name": "Application for Foreign Education Loan Scheme / Videsha Vidhyavikasa / Rajashree Shaumaharaj Foreign Study Scheme", "department_id": 1150, "department_name": "Karnataka Minorities Development Corporation (KMDC)", "definition": "A loan up to Rs. 7,50,000 per annum for 2 years for higher education abroad.", "eligibility": "Must belong to the OBC – Veerashaiva Lingayat Community. Annual family income up to Rs. 8,00,000. Age: 18–35 years.", "procedure": ["The applicant submits the application.", "The application reaches the Case Worker (L1 Officer) at the District Level.", "The verified application moves to the Program Officer (L2 Officer) at the District Level.", "Then to the Disbursement Officer (L3 Officer) at the State Level.", "Finally, it is pushed to DBT for disbursement."], "supporting_documents": ["Aadhaar Card", "Caste Certificate", "Income Certificate", "Parent Approval Letter", "Collateral Letter"], "charges": "Rs. 30"},
        {"scheme_id": 6, "scheme_name": "Ganga Kalyana Scheme / Jeevajala Scheme / Jijaavu Jalabhagya Yojane", "department_id": 1150, "department_name": "Karnataka Minorities Development Corporation (KMDC)", "definition": "Financial assistance up to Rs. 4.5 lakh for drilling a borewell, installing a pump set, and energizing it.", "eligibility": "Small and marginal farmers. Annual family income up to Rs. 98,000 in rural areas or Rs. 1,20,000 in urban areas.", "procedure": ["The applicant submits the application.", "The application reaches the Case Worker (L1 Officer) at the District Level.", "The verified application moves to the Program Officer (L2 Officer) at the District Level.", "Then to the Disbursement Officer (L3 Officer) at the State Level.", "Finally, it is pushed to DBT for disbursement."], "supporting_documents": ["Small & Marginal Farmer Certificate."], "charges": "Rs. 30"},
        {"scheme_id": 1, "scheme_name": "Arivu Educational Renewal Loan Scheme", "department_id": 1150, "department_name": "Karnataka Minorities Development Corporation (KMDC)", "definition": "You will receive a loan up to Rs. 1 lakh at an interest rate of 2% per annum.", "eligibility": "Must have passed the previous year’s examination.", "procedure": ["The applicant submits the application.", "The application reaches the Case Worker (L1 Officer) at the District Level for verification.", "The verified application moves to the Program Officer (L2 Officer) at the District Level.", "The application then goes to the Disbursement Officer (L3 Officer) at the State Level.", "Finally, the application is pushed from the Disbursement Officer to DBT."], "supporting_documents": ["Fee Receipt", "Study Certificate", "Claim Letter including Sanction Order", "Previous Year Marksheet", "Parent Approval Letter", "Collateral Letter"], "charges": "Rs. 30"},
        {"scheme_id": 2, "scheme_name": "Traditional Artisans Scheme / Kayaka Kirana", "department_id": 1150, "department_name": "Karnataka Minorities Development Corporation (KMDC)", "definition": "You will receive a loan between Rs. 50,000 to Rs. 1,00,000 at 2% annual interest. A subsidy of 20% of the loan amount or a maximum of up to Rs. 20,000 will be provided.", "eligibility": "Traditional artisans and skilled occupation holders.", "procedure": ["The applicant submits the application.", "The application reaches the Case Worker (L1 Officer) at the District Level for verification.", "The verified application moves to the Program Officer (L2 Officer) at the District Level.", "The application then goes to the Disbursement Officer (L3 Officer) at the State Level.", "Finally, the application is pushed from the Disbursement Officer to DBT."], "supporting_documents": ["Aadhaar Card", "Caste Certificate", "Income Certificate"], "charges": "Rs. 30"}
    ]
    
    try:
        # Step 1: Connect to the SQLite database
        conn = sqlite3.connect(db_file)
        cursor = conn.cursor()
        print(f"Successfully connected to SQLite database: {db_file}")

        # Step 2: Create the 'schemes' table
        create_table_query = """
        CREATE TABLE IF NOT EXISTS schemes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            scheme_id INTEGER,
            scheme_name TEXT NOT NULL,
            department_id INTEGER,
            department_name TEXT,
            definition TEXT,
            benefits TEXT,
            eligibility TEXT,
            procedure TEXT,
            supporting_documents TEXT,
            required_information TEXT,
            charges TEXT
        );
        """
        cursor.execute(create_table_query)
        print("Table 'schemes' created successfully.")

        # Step 3: Insert data into the table
        insert_query = """
        INSERT INTO schemes (
            scheme_id, scheme_name, department_id, department_name, definition,
            benefits, eligibility, procedure, supporting_documents, required_information, charges
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
        """
        
        for scheme in schemes_data:
            # Prepare data, converting lists to JSON strings and handling missing keys
            data_tuple = (
                scheme.get('scheme_id'),
                scheme.get('scheme_name'),
                scheme.get('department_id'),
                scheme.get('department_name'),
                scheme.get('definition'),
                scheme.get('benefits'),
                json.dumps(scheme.get('eligibility')) if isinstance(scheme.get('eligibility'), list) else scheme.get('eligibility'),
                json.dumps(scheme.get('procedure')) if scheme.get('procedure') is not None else None,
                json.dumps(scheme.get('supporting_documents')) if scheme.get('supporting_documents') is not None else None,
                json.dumps(scheme.get('required_information')) if scheme.get('required_information') is not None else None,
                scheme.get('charges')
            )
            cursor.execute(insert_query, data_tuple)

        # Commit the transaction to save the changes
        conn.commit()
        print(f"{len(schemes_data)} records inserted successfully into 'schemes' table.")

        # Step 4: Verification - Query the database and print a few records
        print("\n--- Verification ---")
        print("Fetching top 3 inserted records:")
        cursor.execute("SELECT scheme_id, scheme_name, department_name FROM schemes LIMIT 3;")
        records = cursor.fetchall()
        for record in records:
            print(f"ID: {record[0]}, Name: {record[1]}, Dept: {record[2]}")
            
    except sqlite3.Error as error:
        print(f"Error while creating SQLite database: {error}")
    finally:
        # Close the database connection
        if conn:
            conn.close()
            print("\nThe SQLite connection is closed.")

if __name__ == '__main__':
    create_database()